### ISSUE TITLE
'HARFBUZZ' has no attribute 'message_func_t'

### ISSUE THREAD

**Issue by adrientetar** [ldo/harfpy#2]
I got this error message while trying to set up a debugger function on the Buffer object:

~~~bash
Traceback (most recent call last):
  File "harfbuzz__.py", line 47, in <module>
    shape_dat(*sys.argv[1:])
  File "harfbuzz__.py", line 28, in shape_dat
    buf.set_message_func(debugger, None, None)
  File "c:\users\admin\downloads\harfpy\harfbuzz.py", line 772, in set_callback
    wrap_callback_func = def_wrap_callback_func(self, callback_func, user_data)
  File "c:\users\admin\downloads\harfpy\harfbuzz.py", line 2484, in def_wrap_message_func
    @HB.message_func_t
AttributeError: type object 'HARFBUZZ' has no attribute 'message_func_t'
~~~

Maybe I'm misusing the API, but thought I would post this.

**Comment by ldo** [comment]
`message_func_t` should be `buffer_message_func_t`. Fixed.
