### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by adrientetar** [ldo/harfpy#4]
I store a hb.Font and reuse it to redo shaping on new inputs, and it seems I randomly get bad access or garbage results after a few times reusing the hb.Font.

~~~bash
Traceback (most recent call last):
  File "c:\users\admin\downloads\trufont\lib\trufont\controls\glyphCanvasView.py", line 342, in keyPressEvent
    self._redirectEvent(event, self._currentTool.keyPressEvent)
  File "c:\users\admin\downloads\trufont\lib\trufont\controls\glyphCanvasView.py", line 465, in _redirectEvent
    callback(event)
  File "c:\users\admin\downloads\trufont\lib\trufont\drawingTools\textTool.py", line 119, in keyPressEvent
    self.layoutLine.insert(text)
  File "c:\users\admin\downloads\trufont\lib\trufont\objects\layoutLine.py", line 99, in insert
    self.updateView()
  File "c:\users\admin\downloads\trufont\lib\trufont\objects\layoutLine.py", line 164, in updateView
    self._shapeAndSetText()
  File "c:\users\admin\downloads\trufont\lib\trufont\objects\layoutLine.py", line 142, in _shapeAndSetText
    records = self.engine.process(self._inputString.tounicode())
  File "c:\users\admin\downloads\trufont\lib\trufont\objects\layoutEngine.py", line 165, in process
    hb.shape(self._hbFont, buf)
  File "c:\users\admin\downloads\harfpy\harfbuzz.py", line 4009, in shape
    hb.hb_shape(font._hbobj, buffer._hbobj, c_features, nr_features)
OSError: exception: access violation reading 0x130945F6
~~~

**Comment by adrientetar** [comment]
Apparently that happened because I didn't keep a reference to the array I use to make my hb.Blob object. Closing.

**Comment by ldo** [comment]
If you call `Blob.create_for_array()`, it should be keeping a reference to your array for itself. Were you using `Blob.create()` instead?

**Comment by adrientetar** [comment]
I use create_for_array (the code is similar to #3) but I delete the Blob object soon after. Should I keep a reference to the Blob object itself? It works fine keeping a reference to the array.

**Comment by ldo** [comment]
Oh I see: the `Blob` is created from the array, then then `Face` from the `Blob`, and the `Font` from the `Face`. So if the array object disappears, then the storage for all of these becomes invalid.

So yes, your workaround is the correct one for now. Should I be keeping references to the array object in all of these to keep it from disappearing?

**Comment by adrientetar** [comment]
> Should I be keeping references to the array object in all of these to keep it from disappearing?

That would fix it. Not that I mind keeping a reference manually.

**Comment by adrientetar** [comment]
Actually yeah, storing a reference through the Font object would be nice.

**Comment by ldo** [comment]
OK, I have done this. Unfortunately I can’t handle the `Face.create_for_tables` case--you’re still on your own there.
